# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'ESPictureBrowserDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ESPictureBrowserDemo

pod 'AsyncDisplayKit', '~> 1.9.90'

end
