# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESPictureBrowserDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESPictureBrowserDemo

pod 'AsyncDisplayKit', '~> 1.9.90'
pod 'YYWebImage', '~> 1.0.5'

end
